function notifyMe(message,status,progress){if(!("Notification"in window)){alert("This browser does not support desktop notification");}else if(Notification.permission==="granted"){var options={body:message,icon:"path/images/logo.png",dir:"auto"};var notification=new Notification("[vChecker] "+ status,options);}else if(Notification.permission!=='denied'){Notification.requestPermission(function(permission){if(!('permission'in Notification)){Notification.permission=permission;}
if(permission==="granted"){var options={body:progress,icon:"path/images/logo.png",dir:"auto"};var notification=new Notification("[vChecker] "+ status,options);}});}}
var audio=new Audio('path/sound/blop.mp3');var audio2=new Audio('path/sound/bot.mp3');function limpar(){var ccs=$('#ccs').val();if(ccs.length==0){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Carregue a lista antes de limpa-la!</div>';notifyMe("Nós não consiguimos limpar algo que já está limpo!","Erro a limpar a lista de checagem.");audio2.play();return;}else{document.getElementById("ccs").value='';document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Lista limpa.</div>';audio.play();notifyMe("Todas as ccs que estavam na sua lista foram limpas!","Lista limpa.");}}
function rmLinha(id){var lines=$(id).val().split('\n');lines.splice(0,1);$(id).val(lines.join("\n"));}
function start(){var ccs=$('#ccs').val();if(ccs.length==0){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Carregue a lista!</div>';notifyMe("Você precisa carregar uma lista antes de iniciar o testador!","Erro ao iniciar.");audio2.play();return;}else{document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Iniciado.</div>';audio.play();notifyMe("Suas lista para checagem das cc's foi enviada com sucesso, estamos iniciando o testador!","Iniciando testes.");}
var i;var ccs=$('#ccs').val();var cc=ccs.split("\n");var separador=$('#separador').val();for(i=0;i<cc.length;i++){var cc2=cc[i];var id=i;check(cc2,separador,id);}
function stop(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Carregue a lista!</div>';notifyMe("Você precisa carregar uma lista antes de iniciar o testador!","Erro ao iniciar.");audio2.play();}
var textarea=document.getElementById("ccs").value;var textareacount=textarea.split('\n');var textareaMatch=count(textareacount,'COUNT_RECURSIVE');var myString=textarea;var myArray=listToArray(myString,'\n');document.getElementById("carregada").innerHTML=textareaMatch;for(var i=0;i<textareaMatch;i++){var cclst=myArray[i];var cemail=cclst.split(";");var csids='csid_'+ i;var ccids='ccid_'+ i;var output=document.getElementById("ccs").value;var replaced=ccs.split('\n');for(var i=replaced.length;i<0;i++){var item=replaced[i].split(';');}
output=output.replace(cclst,"");output=output.replace("\n","");document.getElementById("ccs").innerHTML=output;console.log(output);}}
function check(cc2,separador,id){setTimeout(function(){$.ajax({type:'GET',url:'function/ajax_gerada_gate_br_1.php',dataType:'html',data:{'testar':'cc','ccs':cc2,'separador':separador},success:function(msg)
{document.getElementById("testado").innerHTML=(eval(document.getElementById("testado").innerHTML)+ 1);if(msg.indexOf("Aprovada")>0){document.getElementById("CLIVE").innerHTML=(eval(document.getElementById("CLIVE").innerHTML)+ 1);$("#aprovadas").prepend(msg);rmLinha('#ccs');notifyMe("Você tem mais 1 cc aprovada.","info debitada!");audio.play();document.getElementById("demo").innerHTML='<div class="label label-success label-dismissible">Aprovada.</div>';setTimeout(function(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Testando.</div>';},500);setTimeout(function(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Testando..</div>';},750);setTimeout(function(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Testando...</div>';},1000);console.log('{"Success":"',document.getElementById("testado").innerHTML,'":"true"}')}else{$("#reprovadas").prepend(msg);rmLinha('#ccs');document.getElementById("CDIE").innerHTML=(eval(document.getElementById("CDIE").innerHTML)+ 1);document.getElementById("demo").innerHTML='<div class="label label-danger label-dismissible">Reprovada.</div>';setTimeout(function(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Testando.</div>';},500);setTimeout(function(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Testando..</div>';},750);setTimeout(function(){document.getElementById("demo").innerHTML='<div class="label label-warning label-dismissible">Testando...</div>';},1000);console.log('{"Success":"',document.getElementById("testado").innerHTML,'":"false"}')}}});},id*2000);}
function SelectAll(id){document.getElementById(id).focus();document.getElementById(id).select();}
function listToArray(fullString,separator){var fullArray=[];if(fullString!==undefined){if(fullString.indexOf(separator)==-1){fullArray.push(fullString);}else{fullArray=fullString.split(separator);}}
return fullArray;}
function count(mixed_var,mode){var key,cnt=0;if(mixed_var===null||typeof mixed_var==='undefined'){return 0;}else if(mixed_var.constructor!==Array&&mixed_var.constructor!==Object){return 1;}
if(mode==='COUNT_RECURSIVE'){mode=1;}
if(mode!=1){mode=0;}
for(key in mixed_var){if(mixed_var.hasOwnProperty(key)){cnt++;if(mode==1&&mixed_var[key]&&(mixed_var[key].constructor===Array||mixed_var[key].constructor===Object)){cnt+=this.count(mixed_var[key],1);}}}
return cnt;}
function pushcsB(c,p){document.getElementById(p).innerHTML=document.getElementById(p).innerHTML+ c+"\n<br>";}